#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


source ./bashdev-video


video::ffmpegIsInstalled && RESULT=true || RESULT=false
echo "info: ffmpeg installed        $RESULT"

#video::ffmpegVersionGet

echo "info  ffmpeg version          $( video::ffmpegVersionGet )"

echo "info: x265 CPU encode support $( video::supportffmpegCPUEncodeHEVC && echo true || echo false )"

