#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


source ./bashdev-gpu


echo "info: GPU brand        $(gpu::brandGet)"
echo "info: GPU model        $(gpu::modelGet)"

echo "info: GPU frequency    $(gpu::frequencyGet)"
echo "info: GPU temperature  $(gpu::temperatureGet)"

echo "info: GPU HEVC encode  $( gpu::supportEncodeHEVC && echo true || echo false )"


# monitor frequency and return average

DURATION=8
echo "starting frequency monitor $DURATION seconds ..."
echo "starting temperature monitor $DURATION seconds ..."

gpu::frequencyWatcherStart 2
gpu::temperatureWatcherStart 2

sleep "$DURATION"

echo "info:  Average frequency $(gpu::frequencyWatcherStop)"
echo "info:  Average temperature $(gpu::temperatureWatcherStop)"


