#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


# Guard against multiple inclusion

[[ -n "${__BASHDEV_SYSTEM_SH__}" ]] && return ; readonly __BASHDEV_SYSTEM_SH__=1


system::isInstalled()     { command -v "$1" >/dev/null 2>&1; }

system::notifyInstalled() {

    local RESULT=0

    if system::isInstalled "$1"; then
      echo "info:  $1 is installed"

    else
      RESULT=$?
      echo "warning: $1 is not installed"
    fi

    return $RESULT;
}

system::notifyMultipleInstalled() { for util in $@; do system::notifyInstalled "$util"; done }
