#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


source ./bashdev-app

APP_NAME=$(basename "$0")
APP_VERSION="0.0.1"
APP_AUTHOR="Tom Brown"
APP_YEAR="2025"
APP_LICENSE="MIT"
APP_DESC="bashdev-app library test bed and sample code"

app::masthead "$APP_NAME" "$APP_VERSION" "$APP_AUTHOR" "$APP_YEAR" "$APP_LICENSE" "$APP_DESC"

DEBUG=false

# process lock

app::processLockSpin $(basename "$0") 500 2 10

echo "sleep 5s"
sleep 20


# release the lock on and remove lock file the way out

app::processUnlock
