#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


# Guard against multiple inclusion

[[ -n "${__BASHDEV_VIDEO_SH__}" ]] && return ; readonly __BASHDEV_VIDEO_SH__=1


video::ffmpegIsInstalled() { command -v ffmpeg >/dev/null 2>&1; }

video::ffmpegVersionGet() { ffmpeg -version 2>/dev/null | awk 'NR==1 { print $3 }'; }

video::supportffmpegCPUEncodeHEVC() { ffmpeg -hide_banner -encoders 2>/dev/null | grep -qE 'V.*libx265'; }
