#!/bin/bash

#
# bashdev - BASH general purpose libraries
# Copyright (C) 2025 Tom Brown
#
# This file is part of bashdev
#
# bashdev is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashdev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashdev.  If not, see <https://www.gnu.org/licenses/>.
#


source bashdev-sensor

sensor::envTempSensorPresent && RESULT=true || RESULT=false
echo "info: env temp sensor detect    $RESULT"
echo "info: environment temperature   $(sensor::envTempGet)"


# monitor temperature return average

DURATION=15
echo "starting temperature monitor $DURATION seconds ..."

sensor::envTempWatcherStart 5

sleep "$DURATION"

echo "Average temperature $(sensor::envTempWatcherStop)"


